# Site settings
title: My Test Blog
email: homerhanumat SPAM_BLOCKgmaildotcom
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome blog.
baseurl: "/knitr-jekyll/" # the subpath of your site, e.g. /blog/
url: "https://homerhanumat.github.io" # the base hostname & protocol for your site
twitter_username: homerhanumat
github_username:  homerhanumat
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
