# Site settings
title: A Statistics Blog
email: homerhanumat SPAM_BLOCKgmaildotcom
description: > # this means to ignore newlines until "baseurl:"
  A blog devoted mostly to the the teaching of undergraduate-level statstics
  and data anlysis with R, along with occasional technical notes on R-related
  tools.
baseurl: "/knitr-jekyll/" # the subpath of your site, e.g. /blog/
url: "https://homerhanumat.github.io" # the base hostname & protocol for your site
twitter_username: homerhanumat
github_username:  homerhanumat
permalink: /:year/:month/:title.html
author:  Homer White

# Build settings
markdown: kramdown
